### ISSUE TITLE
Missing Decryption on Credential Types

### ISSUE THREAD

**Issue by slyd0g** [thesubtlety/go-decrypt-jenkins#3]
Hello,

I noticed that not all of the credentials within credentials.xml were being decrypted even though I had all of the secret material.

I noticed that `Plugins` within `workerplugins.go` was missing the following:

- "com.cloudbees.jenkins.plugins.awscredentials.AWSCredentialsImpl",
- "io.jenkins.plugins.oidc__provider.IdTokenFileCredentials",
- "org.jenkinsci.plugins.github__branch__source.GitHubAppCredentials",
- "com.datapipe.jenkins.vault.credentials.VaultAppRoleCredential",

After adding them, the credentials were decrypted properly. I tried to make a PR, but I believe write permission is disabled.

Thanks,

- Justin Bui

**Comment by thesubtlety** [comment]
Awesome, thank you! Haven't looked at this in a while - those are some useful plugins to have coverage for. I'll get this updated but can you provide a specific error with the write permission issue so I can look into it?

Also for one off cases you can specify xml search string too like `-p com.cloudbees.jenkins.plugins.awscredentials.AWSCredentialsImpl`

**Comment by slyd0g** [comment]
Oh awesome on the `-p` flag! Thanks for adding the plugins in :D

🤦‍♀️  sorry, I just checked again and I can open up a PR. I was so use to opening branches directly on a repo and PRing those back to main. Just tried to fork, modify, PR, and that worked! This can be closed out, thank you!
